include_paths = ["src/**/*.ts"]
ignore_paths = ["src/web/resource/survey/*.html"]

words = [
    "autocheckpoint",
    "checkpointing",
    "connectivities",
    "cron",
    "csr",
    "dbstat",
    "derivables",
    "despawn",
    "despawn",
    "despawned",
    "effectful",
    "errno",
    "fns",
    "freelist",
    "hass",
    "hono",
    "lifecycle",
    "mountpoint",
    "ohf",
    "pgsize",
    "postflight",
    "preflight",
    "rethrowing",
    "seaweedfs",
    "sqlc",
    "ssr",
    "suspendable",
    "suspendable",
    "timespan",
    "unhashed",
    "unkeyed",
    "vfs",
]
