create index snapshot_submission_attribution_device_permutation_link_snapshot_submission_device_permutation_link_id_idx on snapshot_submission_attribution_device_permutation_link(snapshot_submission_device_permutation_link_id);
create index snapshot_submission_attribution_set_entity_device_permutation_snapshot_submission_set_entity_device_permutation_id_idx on snapshot_submission_attribution_set_entity_device_permutation (snapshot_submission_set_entity_device_permutation_id);

create index snapshot_submission_set_entity_device_permutation_snapshot_submission_device_permutation_id_idx on snapshot_submission_set_entity_device_permutation(snapshot_submission_device_permutation_id);
