name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          lfs: true

      - name: configure credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b  # v6.2.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: login to ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64  # v2.1.6

      - name: set up qemu
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3  # v4.1.0

      - name: set up docker buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5  # v4.1.0

      - name: build and push
        id: push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf  # v7.2.0
        env:
          ECR_TAG_LATEST: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:latest
          ECR_TAG_COMMIT: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}
        with:
          context: project/server
          platforms: linux/amd64,linux/arm64
          build-contexts: |
            client=project/client
            schema=schema
            sqlc-plugin=tool/sqlc-generate-typescript-plugin/target/wasm32-wasip1/release
          push: true
          tags: ${{ env.ECR_TAG_LATEST }},${{ env.ECR_TAG_COMMIT }}
          # inline caching isn't particularly effective 🫤
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: generate artifact attestation
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26  # v4.1.0
        with:
          subject-name: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: update task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@6853cfae8c3a7d978fbf68b5a55453395541dfbb  # v1.8.5
        with:
          task-definition: project/server/vendor/aws/ecs-task-definition.json
          container-name: ${{ vars.ECS_TASK_DEFINITION_CONTAINER_NAME }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}

      - name: deploy task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@a310a830f5c14e583e35d84e4e1ec7dd177c3c9c  # v2.6.2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ vars.ECS_SERVICE }}
          cluster: ${{ vars.ECS_CLUSTER }}
          wait-for-service-stability: true
          service-managed-ebs-volume-name: "snapshot0"
          service-managed-ebs-volume: '{"filesystemType": "xfs", "iops": 5000, "sizeInGiB": 50, "throughput": 800, "volumeType": "gp3", "encrypted": false, "roleArn": "arn:aws:iam::647181292512:role/ohf-device-database-infrastructure-role"}'
